# Generated by Django 3.0.5 on 2024-08-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('search_engine', models.CharField(max_length=50)),
                ('localization', models.CharField(blank=True, max_length=50)),
                ('search_type', models.CharField(blank=True, max_length=50)),
                ('pagination', models.CharField(blank=True, max_length=50)),
                ('geo_location', models.CharField(blank=True, max_length=50)),
                ('device', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
