# Generated by Django 3.0.5 on 2024-08-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchquery',
            old_name='localization',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='search_type',
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='geo_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
