# Generated by Django 3.0.5 on 2024-08-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_auto_20240811_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchquery',
            old_name='geo_location',
            new_name='city',
        ),
    ]
