# Generated by Django 3.0.5 on 2024-08-13 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_auto_20240811_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='keywords',
            field=models.TextField(default='default_keyword1,default_keyword2,default_keyword3'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
