# Generated by Django 3.0.5 on 2024-08-14 09:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0004_auto_20240813_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchquery',
            old_name='timestamp',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 9, 50, 26, 137406, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='keywords',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('timestamp', models.DateTimeField()),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='search_app.SearchQuery')),
            ],
        ),
    ]
