# Generated by Django 3.2.25 on 2024-08-24 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0007_auto_20240815_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchresult',
            name='search_query',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='url',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='brand_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='comp_split',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='day',
            field=models.CharField(default='Weekday', max_length=10),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='display_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='global_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='hour',
            field=models.CharField(default='00:00', max_length=20),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='isd_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='isd_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='spectrum_vs_comp',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='us_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='us_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='keyword',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
