# Generated by Django 3.2.25 on 2024-08-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0008_auto_20240824_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchresult',
            name='type',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='result_type',
            field=models.CharField(default='organic', max_length=50),
        ),
    ]
